### ISSUE TITLE
Build for v0.26.0

### ISSUE THREAD

**Issue by squat** [Saiyato/snapclient_docker#6]
Would it be possible to get the images built for v0.26.0 of snapcast for both the snapclient and snapserver binaries? Perhaps it would be easiest to set up a GitHub Actions workflow that is triggered automatically every day and runs the build to ensure that the latest tag is always available.

**Comment by Saiyato** [comment]
Setting up proper actions is on my wish list, but haven't had the time to set them up properly. Mostly because it needs to be multi-arch.

Regarding the version you're referencing, those are the versions in the images if I'm not mistaken. Am I missing something? v0.26.0 was released in December 2021. The containers don't even use official builds, it's all built from source, normally I would argue that it's not always advised, but nothing has changed since December 2021. :wink:

```
ubuntu@mypc:~$ docker run saiyato/snapclient -v
Unable to find image 'saiyato/snapclient:latest' locally
latest: Pulling from saiyato/snapclient
97518928ae5f: Already exists
1938c00e807d: Pull complete
d3386b5343e7: Pull complete
4e80b4c5a4aa: Pull complete
Digest: sha256:795fc176ac74397f8d4338b79ef623234735181c8019d4ff99c7df77a983e96c
Status: Downloaded newer image for saiyato/snapclient:latest
snapclient v0.26.0
Copyright (C) 2014-2021 BadAix (snapcast@badaix.de).
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by squat** [comment]
ack, you're totally, right, the image I was looking at was cached from before December.
Agreed that multi-arch builds are a must. Need to take a closer look at your build scripts, but there are good actions to build multi-arch docker images that can hopefully be re-used here. Also, it would be an extra nice-to-have for the actions to produce images with tags corresponding to Snapcast releases and not _just_ latest.
